# Auto-generated by Terraform — fill in before running `terraform apply`
aws_region       = "ap-south-1"
instance_type    = "t3.micro"
key_name         = "chloi-key"            # <-- replace with your EC2 Key Pair name
allowed_ssh_cidr = "0.0.0.0/0"            # <-- restrict to your IP for production
